### ISSUE TITLE
Can't delete an access restriction

### ISSUE THREAD

**Issue by abjennings** [ReliefLabs/EasyTomato#56]
When I click the "Delete..." button on the "Edit Access Restrictions" page, the button disappears and nothing else happens.

This is because the 

```
onclick='remove()'
```

in release/src/router/www/restrict-edit.asp is not calling the remove function defined in that file.  I think it is getting confused with a "remove" function added globally, via the prototype, to one of the classes.

I have a patch that I think will work (renaming that function), but I haven't tested it.

Is this something exclusive to EasyTomato (specific to the Javascript frameworks that ET pulls in)?  Or is it something that should be fixed in an upstream project (TomatoUSB)?  If you point me in the right direction, I can go there.

If it belongs here, should I submit a pull request, or fork and fix, or what?

**Comment by abjennings** [comment]
Here is the patch that I think will work, but haven't tested:
https://gist.github.com/abjennings/6647552

**Comment by fougner** [comment]
I believe this is fixed upstreams already, and will be fixed in EasyTomato the next time we merge from upstreams. Do you want me to upload a new build with the new fixes applied ?

http://repo.or.cz/w/tomato.git/blobdiff/13f9592d318311a4e711d001699eb5574e0b4a21..95be6193640542c61d55ec742b030a1f93bb80ff:/release/src/router/www/restrict-edit.asp

**Comment by abjennings** [comment]
You don't have to upload a new build for me.  I figured out a workaround
that's good enough for me.  (Open a javascript console and type "remove()".)

**Comment by fougner** [comment]
Hiya!
I've merged the latest changes from upstream and built a new firmware. I'd be grateful if you could try this build and report back if the bug is fixed, then I can mark this report as fixed.

I've tried this on my RT-N16 and it works! https://dl.dropboxusercontent.com/u/103754/tomato-K26USB-1.28.MIPSR2-VPN-NOCAT.trx

**Comment by abjennings** [comment]
The restrict-edit.asp page is now messed up (like a css file is missing).
Screenshot attached.

But the delete button did work.

**Comment by fougner** [comment]
Ah, my bad. Here's a new one where the bug is fixed and CSS works.

https://dl.dropboxusercontent.com/u/103754/tomato-K26USB-1.28.7503-MIPSR2-EasyTomato-VPN-NOCAT.trx

**Comment by abjennings** [comment]
Yes, that works.  Thanks.
